"""agregar_descripcion_producto

Revision ID: 12604612d514
Revises: d6a0d4646167
Create Date: 2025-11-22 14:19:31.472699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12604612d514'
down_revision: Union[str, Sequence[str], None] = 'd6a0d4646167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('descripcion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'descripcion')
    # ### end Alembic commands ###
