"""actualizacion_final_models

Revision ID: d6a0d4646167
Revises: 4cf3fc25bfd0
Create Date: 2025-11-22 14:10:00.258847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a0d4646167'
down_revision: Union[str, Sequence[str], None] = '4cf3fc25bfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajuste_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cantidad_sistema', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_fisica', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('diferencia', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Text(), nullable=False),
    sa.Column('cantidad_anterior', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_movida', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cantidad_nueva', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('corte_caja', sa.Column('ventas_totales', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('corte_caja', sa.Column('efectivo_esperado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('corte_caja', sa.Column('efectivo_real', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('corte_caja', sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('corte_caja', sa.Column('monto_retirado', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('corte_caja', sa.Column('fondo_siguiente', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('corte_caja', 'efectivo_final_real')
    op.drop_column('corte_caja', 'varianza')
    op.add_column('producto', sa.Column('unidad_medida', sa.Text(), server_default='pza', nullable=False))
    op.add_column('producto', sa.Column('contenido_neto', sa.Numeric(precision=10, scale=3), server_default='1.0', nullable=False))
    op.add_column('producto', sa.Column('se_vende_a_granel', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('producto', sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('producto', sa.Column('precio_granel', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('producto', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_unique_constraint(None, 'producto', ['sku'])
    op.drop_constraint(op.f('producto_subcategoria_id_fkey'), 'producto', type_='foreignkey')
    op.drop_constraint(op.f('producto_marca_id_fkey'), 'producto', type_='foreignkey')
    op.create_foreign_key(None, 'producto', 'subcategoria', ['subcategoria_id'], ['id'])
    op.create_foreign_key(None, 'producto', 'marca', ['marca_id'], ['id'])
    op.drop_column('producto', 'se_vende_por_kilo')
    op.drop_column('producto', 'precio_unitario')
    op.drop_column('producto', 'unidad')
    op.drop_column('producto', 'precio_por_kg')
    op.drop_column('producto', 'peso_bulto_kg')
    op.drop_column('producto', 'precio_por_bulto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('precio_por_bulto', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('peso_bulto_kg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('precio_por_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('unidad', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('producto', sa.Column('se_vende_por_kilo', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.drop_constraint(None, 'producto', type_='foreignkey')
    op.create_foreign_key(op.f('producto_marca_id_fkey'), 'producto', 'marca', ['marca_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('producto_subcategoria_id_fkey'), 'producto', 'subcategoria', ['subcategoria_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'producto', type_='unique')
    op.alter_column('producto', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('producto', 'precio_granel')
    op.drop_column('producto', 'precio_base')
    op.drop_column('producto', 'se_vende_a_granel')
    op.drop_column('producto', 'contenido_neto')
    op.drop_column('producto', 'unidad_medida')
    op.add_column('corte_caja', sa.Column('varianza', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('corte_caja', sa.Column('efectivo_final_real', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('corte_caja', 'fondo_siguiente')
    op.drop_column('corte_caja', 'monto_retirado')
    op.drop_column('corte_caja', 'diferencia')
    op.drop_column('corte_caja', 'efectivo_real')
    op.drop_column('corte_caja', 'efectivo_esperado')
    op.drop_column('corte_caja', 'ventas_totales')
    op.drop_table('historial_inventario')
    op.drop_table('ajuste_inventario')
    # ### end Alembic commands ###
